services:
  db:
    image: mysql:9.6.0
    container_name: mysql-todo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 666666
      MYSQL_DATABASE: todo
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis-todo
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  mysql-data:
  redis-data:
